name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
   build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.5.2
      
      - name: npm install
        run: npm install
        
      - name: mocha install  
        run: npm install -g mocha
        
      - name: Test something
        run: echo "Test CI/CD without command"
      - name: npm install 
        run: npm install mocha azure-pipelines-task-lib sync-request @types/q @types/node
        
      - name: Test Mocha
        run: mocha tasks/tests/_suite.js

