name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
   build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.5.2
      
      - name: npm install main package.json
        run: npm install --prefix
      - name: npm install tasks package.json
        run: npm install --prefix tasks
      - name: Test something
        run: echo "Test CI/CD without command"
        
      # - name: Test Mocha
      #   run: mocha tasks/tests/_suite.js

