name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
   build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.5.2

      - name: npm install main package.json
        run: npm install

      - name: npm install tasks package.json
        run: |
          cd tasks
          npm install
          npm i -g uuid@latest
          npm  i mocha

      - name: Test something
        run: echo "Test CI/CD without command"
      - name: Test Mocha
        run: |
          cd tasks
          tsc
          npm test 
      - name: Create Azure DevOps extension
        run: |
          npm install -g tfx-cli@latest
          npm run build
        shell: bash
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-ci-build
          path: ./*.vsix

